# Generated by Django 4.0.4 on 2022-08-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('starting_bid', models.IntegerField()),
                ('image', models.URLField()),
                ('categories', models.CharField(max_length=64)),
            ],
        ),
    ]
