# Generated by Django 4.1 on 2023-06-09 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_commentsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsmodel',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlisting'),
        ),
    ]
